# Generated by Django 5.1.3 on 2024-12-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='recycle',
            field=models.BooleanField(default=False),
        ),
    ]
