# Generated by Django 5.1.3 on 2024-12-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_discard_products_recycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='total_discarded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='total_recycled',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
