# Generated by Django 5.1.3 on 2024-11-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_days_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='days_left',
        ),
    ]
